- name: Init

  hosts: all

  become: true

  tasks:

    - name: Setup Docker

      block:

        - name: Add Docker GPG apt Key
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Get ubuntu VERSION_CODENAME
          ansible.builtin.command: lsb_release -sc
          register: ubuntu_version_codename
          changed_when: false

        - name: Add Docker Repository
          ansible.builtin.apt_repository:
            repo: "deb https://download.docker.com/linux/ubuntu {{ ubuntu_version_codename.stdout }} stable"
            state: present

        - name: Install Docker
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: present
            update_cache: true

    # - name: 安装 pip
    #   ansible.builtin.package:
    #     name: python3-pip
    #     state: present

    # - name: 安装 Python 库依赖项 docker docker-compose
    #   ansible.builtin.pip:
    #     name:
    #       # - docker
    #       - docker-compose
    #     state: present

    - name: Allow deployer to use Docker
      ansible.builtin.user:
        name: deployer
        groups:
          - docker
        append: true
