- name: Init
  hosts: all
  become: true

  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Install docker and docker-compose
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present
