name: 部署

on:
  push:
    branches: ["feature-cd"]

jobs:
  setup-dns:
    name: 用 Terraform 设置 DNS
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_STAGE }}

    env:
      # TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
      TF_CLOUD_ORGANIZATION: "${{ secrets.TF_CLOUD_ORGANIZATION }}"

      TF_VAR_cloudflare_api_token: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
      TF_VAR_cloudflare_account_id: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
      TF_VAR_cloudflare_zone: "${{ secrets.CLOUDFLARE_ZONE }}"
      TF_VAR_ip: "${{ secrets.IP }}"

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set TF_WORKSPACE
        run: |
          echo "TF_WORKSPACE=$(basename ${{ github.repository }})-${{ vars.ENVIRONMENT_STAGE }}" >> $GITHUB_OUTPUT
          echo "$TF_WORKSPACE"

      - uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -input=false

        # On push to "main", build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        # if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

  deploy:
    name: 用 Ansible 部署

    needs: setup-dns

    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ansible

    steps:
      - uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --verbose
